appweb/appweb/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import RedirectView

from .views import login, logout, home, register


admin.site.site_header = 'Lingwargs | Games'
admin.site.index_title = 'Lingwargs | Games'


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^i18n/', include('django.conf.urls.i18n')),

    #url(r'^$', home, name='home'),
    url(r'^$', RedirectView.as_view(permanent=False, pattern_name='games'), name='home'),
    url(r'^login/$', login, name='login'),
    url(r'^logout/$', logout, name='logout'),
    url(r'^register/$', register, name='register'),

    url(r'^game/engine/', include('engine.urls')),

    url(r'^game/word2def/', include('games.word2def.urls', namespace='word2def')), # TODO: Auto-add because we need namespace to be that 'id',

]

appweb/engine/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from __future__ import absolute_import

from django.conf.urls import include, url
from django.views.generic import ListView, TemplateView
from django.apps import apps
from .models import Game
from .views import GameDetailView, GamePlayView, GameRankingView, UserRankingView


urlpatterns = [
    url(r'^home/$', TemplateView.as_view(template_name='engine/home.html'), name='games'),

    url(r'^(?P<pk>\w+)/detail/$', GameDetailView.as_view(), name='game_detail'),
    url(r'^(?P<pk>\w+)/play/$', GamePlayView.as_view(), name='game_play'),
    url(r'^(?P<pk>\w+)/answer/(?P<uuid>[a-z0-9-]+)/$', GamePlayView.as_view(), name='game_answer'),
    url(r'^(?P<pk>\w+)/ranking/$', GameRankingView.as_view(), name='game_ranking'),

    url(r'^user/ranking/$', UserRankingView.as_view(), name='user_ranking'),
]


# This code is executed only once (on first request).
def execute_once():
    engine_app = apps.get_app_config('engine')
    engine_app.register_games()
execute_once()

appweb/engine/models.py
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.core.urlresolvers import reverse
from django.conf import settings
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone
from django.apps import apps


class GameManager(models.Manager):
    def active(self):
        return self.filter(available=True, active=True)


@python_2_unicode_compatible
class Game(models.Model):
    id = models.CharField(max_length=40, primary_key=True)
    title = models.CharField(max_length=128)
    available = models.BooleanField(default=True)
    active = models.BooleanField(default=True)
    is_app = models.BooleanField()
    author = models.CharField(max_length=60, blank=True, null=True)

    date_added = models.DateTimeField(auto_now_add=True)

    objects = GameManager()
    engine_app = apps.get_app_config('engine')

    def __str__(self):
        return u"%s" % self.title

    def get_absolute_url(self):
        return reverse('game_detail', kwargs={'pk': self.pk})

    @property
    def author2(self):
        game = self.engine_app.games[self.id]
        return getattr(game, 'author', None)

    @property
    def description(self):
        game = self.engine_app.games[self.id]
        return getattr(game, 'description', None)


@python_2_unicode_compatible
class Player(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True)
    game = models.ForeignKey(Game)

    first_played = models.DateTimeField(auto_now_add=True)
    last_played = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return u"%s [%s]" % (self.user, self.game)

    def touch(self, commit=True):
        self.last_played = timezone.now()
        if commit:
            self.save()


@python_2_unicode_compatible
class PlayerScore(models.Model):
    player = models.ForeignKey(Player)
    score = models.FloatField(help_text=_(u"Work as 'points'. Based on this the engine will compute rankings"))
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return u"%s" % self.player

appweb/engine/utils/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from __future__ import absolute_import

import uuid
from django.views.generic import TemplateView
from django.contrib import messages
from django.shortcuts import redirect
from django.core.urlresolvers import reverse
from django.apps import apps
from django.views.generic.detail import SingleObjectMixin
from django.utils.safestring import mark_safe
from django.utils.translation import ugettext_lazy as _
from ..models import Player, PlayerScore, Game


engine_app = apps.get_app_config('engine')


class GameMixinView(SingleObjectMixin):
    queryset = Game.objects.active()

    def get_object(self, pk=None):
        pk = pk or self.kwargs[self.pk_url_kwarg]
        if not hasattr(self, '_object'):
            self._object = self.queryset.get(pk=pk)
        return self._object

    @property
    def game(self):
        return engine_app.games[self.object.id]


class QuestionView(GameMixinView, TemplateView):
    template_name = 'engine/game_play.html'

    @property
    def uuid(self):
        if not hasattr(self, '_uuid'):
            if not 'uuid' in self.kwargs:
                self._uuid = str(uuid.uuid4())
            else:
                self._uuid = self.kwargs['uuid']
        return self._uuid

    def get_answer_template(self, question):
        if 'options' in question:
            return 'engine/_answer_options.html'
        elif 'yesno' in question:
            return 'engine/_answer_yesno.html'
        else:
            return None

    def get_context_data(self, *args, **kwargs):
        question, response = self.make_question()
        question.update({'answer_template': self.get_answer_template(question)})
        self.request.session[self.uuid] = {'question': question, 'response': response}

        context = super(QuestionView, self).get_context_data(*args, **kwargs)
        context.update({'question': question, 'id': self.uuid,})

        answer_url = reverse('game_answer', kwargs={'pk': self.object.pk, 'uuid': self.uuid})
        context.update({'answer_url': answer_url})

        return context

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super(QuestionView, self).get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()

        if not request.session.get(self.uuid, False):
            messages.add_message(request, messages.ERROR, u"Invalid answer identifier")
            return self.get(request, *args, **kwargs)

        data = request.session[self.uuid]
        question = data['question']
        response = data['response']
        score = self.score(question, response, request.POST)

        player, created = Player.objects.get_or_create(user=request.user if request.user.is_authenticated() else None, game=self.object)
        PlayerScore.objects.create(player=player, score=score)
        player.touch()

        redirect_url = reverse('game_play', kwargs={'pk': self.object.pk})
        return redirect(redirect_url)

    def get_question_kwargs(self):
        return {}

    def make_question(self):
        return self.game.make_question(**self.get_question_kwargs())

    def score(self, question, response, user_answer, show_message=True):
        score = self.game.score(response, user_answer)

        if show_message:
            if score > 0:
                icon = 'glyphicon-thumbs-up'
                message_level = messages.SUCCESS
                sr_message = _('Well done')
            else:
                icon = 'glyphicon-thumbs-down'
                message_level = messages.ERROR
                sr_message = _('Error')

            msg = mark_safe(u'<span class="glyphicon %s" aria-hidden="true"></span> '
                            u'<span class="sr-only">%s:</span> '
                            u'%s' % (icon, sr_message, response.get('info', None)))
            messages.add_message(self.request, message_level, msg)

        return score

appweb/engine/views.py
from __future__ import division
from __future__ import absolute_import

import itertools
from django.views.generic import DetailView, TemplateView
from django.core.urlresolvers import reverse
from django.utils import timezone
from django.db.models import Sum, F, FloatField
from django.shortcuts import redirect
from django.contrib.auth import get_user_model
from django.utils.safestring import mark_safe
User = get_user_model()

from .models import Game, Player, PlayerScore
from .utils.views import QuestionView, GameMixinView


class GameDetailView(GameMixinView, DetailView):

    def get_template_names(self):
        names = super(GameDetailView, self).get_template_names()
        return ['%s/game_detail.html' % self.object.id] + names

    def get_context_data(self, **kwargs):
        context = super(GameDetailView, self).get_context_data(**kwargs)

        """
        # Get stats by date-hour
        # TODO: If only by date (just one call to db): http://stackoverflow.com/questions/2278076/count-number-of-records-by-date-in-django
        # TODO: Dynamic zooming: https://github.com/kaliatech/dygraphs-dynamiczooming-example
        qs = PlayerScore.objects.filter(player__game__pk=self.object.id).order_by('timestamp')
        qs_anon = qs.filter(player__user__isnull=True).values_list('timestamp', flat=True)
        qs_player = qs.filter(player__user__isnull=False).values_list('timestamp', flat=True)
        def date_hour(timestamp):
            return timestamp.strftime("%x %H:00")

        game_stats_anon = [[group, len(list(matches))] for group, matches in itertools.groupby(qs_anon, lambda x: date_hour(x))]
        game_stats_player = [[group, len(list(matches))] for group, matches in itertools.groupby(qs_player, lambda x: date_hour(x))]

        context.update({'game_stats_anon': game_stats_anon, 'game_stats_player': game_stats_player})
        """

        # Get stats by date-hour
        #   If I have no data, no one has played!
        # TODO: Time limits
        qs = PlayerScore.objects.filter(player__game__pk=self.object.id).order_by('timestamp')
        qs_anon = qs.filter(player__user__isnull=True).values_list('timestamp', flat=True)
        qs_player = qs.filter(player__user__isnull=False).values_list('timestamp', flat=True)
        def date_hour(timestamp):
            return timestamp.strftime("%x %H:00")

        game_stats_anon = {group: len(list(matches)) for group, matches in itertools.groupby(qs_anon, lambda x: date_hour(x))}
        game_stats_player = {group: len(list(matches)) for group, matches in itertools.groupby(qs_player, lambda x: date_hour(x))}

        print(game_stats_anon)
        game_stats = []
        t = qs.first().timestamp
        last = timezone.now() + timezone.timedelta(hours=1)
        while t <= last:
            key = date_hour(t)
            game_stats.append([key, game_stats_anon.get(key, 0), game_stats_player.get(key, 0)])
            t = t + timezone.timedelta(hours=1)

        context.update({'game_stats': game_stats})
        return context


class GameRankingView(GameMixinView, DetailView):
    template_name = 'engine/game_ranking.html'

    def get_context_data(self, **kwargs):
        context = super(GameRankingView, self).get_context_data(**kwargs)

        now = timezone.now().replace(hour=0, minute=0, second=0)
        players = Player.objects.filter(game=self.object.pk).annotate(sum=Sum('playerscore__score'), count=CountAsFloat('playerscore')).annotate(score=F('sum')/F('count')).order_by('-score', '-count')
        context.update({'players': players})
        return context


from django.db.models.aggregates import Aggregate, Value
class CountAsFloat(Aggregate):
    function = 'COUNT'
    name = 'Count'
    template = '%(function)s(%(distinct)s%(expressions)s)'

    def __init__(self, expression, distinct=False, **extra):
        if expression == '*':
            expression = Value(expression)
        super(CountAsFloat, self).__init__(
            expression, distinct='DISTINCT ' if distinct else '', output_field=FloatField(), **extra)

    def __repr__(self):
        return "{}({}, distinct={})".format(
            self.__class__.__name__,
            self.arg_joiner.join(str(arg) for arg in self.source_expressions),
            'False' if self.extra['distinct'] == '' else 'True',
        )

    def convert_value(self, value, expression, connection, context):
        if value is None:
            return 0
        return int(value)


class UserRankingView(TemplateView):
    queryset = Game.objects.active()
    template_name = 'engine/user_ranking.html'

    def get_context_data(self, **kwargs):
        now = timezone.now().replace(hour=0, minute=0, second=0)
        users = User.objects.annotate(sum=Sum('player__playerscore__score'), count=CountAsFloat('player__playerscore')).annotate(score=F('sum')/F('count')).filter(count__gt=0).order_by('-score', '-count')
        context = super(UserRankingView, self).get_context_data(**kwargs)
        context.update({'users': users})
        return context

class GamePlayView(QuestionView):
    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object.is_app:
            # Redirect to play URL inside app
            return redirect(reverse('%s:play' % self.object.id))
        else:
            return super(GamePlayView, self).get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        answer_url = reverse('game_answer', kwargs={'pk': self.object.pk, 'uuid': self.uuid})
        return super(GamePlayView, self).get_context_data(answer_url=answer_url, game=self.object)

appweb/engine/templates/engine/_answer_options.html
{% load i18n %}

<div class="row">
    <div class="col-md-2">
        {% trans "Select your answer:" %}
    </div>
    <div class="col-md-10">
        <div class="list-group">
            {% for ans in question.options %}
                <a href="#" class="list-group-item" onclick="document.getElementById('answer-{{ forloop.counter0 }}').submit();">
                    &raquo; {{ ans }}
                </a>
                <form class="hidden" id="answer-{{ forloop.counter0 }}" method="POST" action="{{ answer_url }}">{% csrf_token %}
                    <input type="hidden" name="answer" value="{{ forloop.counter0 }}">
                </form>
            {% endfor %}
        </div>
    </div>
</div>

appweb/engine/templates/engine/base.html
{% extends "base.html" %}
{% load i18n appweb %}

{% block content %}
    <div class="col-sm-3 col-md-2 sidebar">
        <h3>{% trans "Challenges" %}</h3>
        {% get_active_games as game_list %}
        {% for game in game_list %}
            {% if forloop.first %}<ul class="nav nav-sidebar">{% endif %}
                <li class="{% active '^/game/'|add:game.id %}"><a href="{{ game.get_absolute_url }}">{{ game }}</a></li>
            {% if forloop.last %}</ul>{% endif %}
        {% endfor %}
    </div>

    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
                <a class="close" data-dismiss="alert">×</a>
                {{ message }}
            </div>
        {% endfor %}

        {% block content_engine %}
        {% endblock %}
    </div>
{% endblock %}

appweb/engine/templates/engine/game_detail.html
{% extends "engine/base.html" %}
{% load i18n static appweb %}

{% block content_engine %}
        <h2>
            {{ game.title }}
            {% if game.author %}
                <small>
                    {% blocktrans with author=game.author %}by {{ author }}{% endblocktrans %}
                </small>
            {% endif %}
        </h2>
        <p>
            {% block game_menu %}
            <ul class="nav nav-tabs">
                {% url 'game_detail' game.id as url_detail %}
                {% url game.id|add:":play" as url_play %}
                {% if not url_play %}
                    {% url 'game_play' game.id as url_play %}
                {% endif %}
                {% url 'game_ranking' game.id as url_ranking %}
                <li role="presentation" class="{% active url_detail %}"><a href="{{ url_detail }}">{% trans "Details" %}</a></li>
                <li role="presentation" class="{% active url_play %}">
                    <a href="{{ url_play }}">
                        <span class="glyphicon glyphicon-play-circle" aria-hidden="true"></span> {% trans "Play" %}
                    </a>
                </li>
                <li role="presentation" class="{% active url_ranking %}"><a href="{{ url_ranking }}">{% trans "Ranking" %}</a></li>
            </ul>
            {% endblock %}
        </p>
        <div>
            {% block content_game %}
                <p>{{ game.description|default:"No description available." }}</p>

                <h3>{% trans "Popularity" %}</h3>
                <p>{% trans "Number of rounds played by registered and anonymous users" %}:</p>
                <div class="col-xs-12">
                    <div id="game-stats"></div>
                </div>
            {% endblock %}
        </div>


{% endblock %}

{% block extra_js %}
            <script src="{% static 'js/dygraph-combined.js' %}"></script>
            <script>
                var drawGraphStats = function() {
                    new Dygraph(document.getElementById("game-stats"),
                        [
                        {% for date,anon,player in game_stats %}
                            [new Date("{{ date }}"), {{ anon }}, {{ player }}],
                        {% endfor %}
                        ],
                        {
                        legend: 'always',
                        drawPoints: false,
                        showRoller: false,
                        labels: ['{% trans "Date" %}', '{% trans "Anonymous" %}', '{% trans "Registered" %}']
                    });
                };

                $(document).ready(function(){
                    drawGraphStats();
                });
            </script>
{% endblock %}

appweb/engine/templates/engine/game_play.html
{% extends 'engine/game_detail.html' %}
{% load i18n %}

{% block content_game %}
        <div class="container-fluid">
            {% block query %}
                <div class="row">
                    <div class="col-md-12">
                        <h3>{% trans "Question" %}: {{ question.query }}</h3>
                    </div>
                </div>
            {% endblock %}
            {% block answer %}
                {% include question.answer_template %}
            {% endblock %}
            </div>
        </div>
{% endblock %}

appweb/engine/templates/engine/game_ranking.html
{% extends "engine/game_detail.html" %}
{% load i18n %}

{% block content_game %}
    <table class="table table-hover">
        <thead>
            <tr>
                <th>#</th>
                <th>{% trans "Player" %}</th>
                <th>{% trans "Points" %}</th>
                <th>{% trans "Rounds" %}</th>
                <th>{% trans "Score" %}</th>
            </tr>
        </thead>
        {% for player in players %}
            <tr>
                <th>{{ forloop.counter }}</th>
                <td>{{ player.user }}</td>
                <td>{{ player.sum|floatformat:"2" }}</td>
                <td>{{ player.count }}</td>
                <td>{{ player.score|floatformat:"2" }}</td>
            </tr>
        {% endfor %}
    </table>

    <hr>
    <p>
        *{% blocktrans %}This ranking is temporal as we design a better ranking algorithm which takes into account number of rounds and time since last play to compute score (<a href="https://github.com/lingwars/lingwars-games/issues/1">ideas?</a>){% endblocktrans %}.
    </p>
    <p>
        {% blocktrans %}Now it is implemented as: <strong>score = points/rounds</strong>{% endblocktrans %}.
    </p>
{% endblock %}

appweb/engine/templates/engine/home.html
{% extends 'engine/base.html' %}

{% load i18n appweb %}

{% block content_engine %}
    <h1>{% trans "Challenges" %}</h1>
    <div>
        <p>
            {% blocktrans %}Here we are offering some challenges to test you. These games have been developed by the <a href="http://lingwars.github.io/blog/" target="_blank">Lingẅars</a> team{% endblocktrans %}.
        </p>

        <div class="row">
            {% get_active_games as game_list %}
            {% for game in game_list %}
                <div class="col-md-4">
                    <h3>
                        {{ game.title }}
                        {% if game.author %}
                            <small>
                                {% blocktrans with author=game.author %}by {{ author }}{% endblocktrans %}
                            </small>
                        {% endif %}
                    </h3>
                    <p>{{ game.description|default:"No description provided" }}</p>
                    <p>
                        <a class="btn btn-default" href="{% url 'game_play' game.id %}" role="button">Play &raquo;</a>
                    </p>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

appweb/engine/templates/engine/user_ranking.html
{% extends "engine/base.html" %}

{% block content_engine %}
    <h2>Global ranking</h2>

    <p>No tengo muy claro qué/cómo mostrar aquí</p>
    <table>
        <thead>
            <th>Player</th>
            <th>Rank</th>
            <th>Points</th>
            <th>Rounds</th>
            <th>Score</th>
        </thead>
        {% for user in users %}
            <tr>
                <td>{{ user }}</td>
                <td>{{ forloop.counter }}</td>
                <td>{{ user.sum|floatformat:"2" }}</td>
                <td>{{ user.count }}</td>
                <td>{{ user.score|floatformat:"2" }}</td>
            </tr>
        {% endfor %}
    </table>

{% endblock %}