games/word2def/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.conf.urls import include, url
from .views import Word2DefQuestionView, ChangeLevelView, save_word, SavedWordList


urlpatterns = [
    url(r'^play/$', Word2DefQuestionView.as_view(), name='play'),
    url(r'^answer/(?P<uuid>[a-z0-9-]+)/$', Word2DefQuestionView.as_view(), name='answer'),
    url(r'^level/$', ChangeLevelView.as_view(), name='change_level'),
    url(r'^save/list$', SavedWordList.as_view(), name='save_word_list'),

    # Ajax views
    url(r'^save/$', save_word, name='save_word'),

]

games/word2def/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django import forms
from django.utils.translation import ugettext_lazy as _

class LevelForm(forms.Form):
    level = forms.ChoiceField([(it, _("Level %d") % it) for it in range(10)])

games/word2def/templates/word2def/_answer_options.html
{% load i18n %}

<div class="row">
    <div class="col-md-2">
        <p>{% trans "Select your answer:" %}</p>
        <p>
        <form id="change_level_form" method="post" action="{% url 'word2def:change_level' %}">{% csrf_token %}
            {{ level_form.level }}
            <input type="hidden" name="next" value="{{ request.path }}">
        </form>
        </p>
    </div>
    <div class="col-md-10">
        <div class="list-group">
            {% for ans in question.options %}
                <a href="#" class="list-group-item" onclick="document.getElementById('answer-{{ forloop.counter0 }}').submit();">
                    &raquo; {{ ans }}
                </a>
                <form class="hidden" id="answer-{{ forloop.counter0 }}" method="POST" action="{{ answer_url }}">{% csrf_token %}
                    <input type="hidden" name="answer" value="{{ forloop.counter0 }}">
                </form>
            {% endfor %}
        </div>
    </div>
</div>

games/word2def/templates/word2def/game_play.html
{% extends 'engine/game_play.html' %}

{% load i18n %}

{% block extra_js %}
        {{ block.super }}
        <script>
            $(document).ready(function(){
                $('#id_level').change(function() {
                    $('#change_level_form').submit();
                });
            });

            $(document).ready(function(){
                $('#save-word').on('click',function(){
                    $.ajax({
                        method: "POST",
                        url: "{% url 'word2def:save_word' %}",
                        data: { word: $(this).attr("word"),
                                csrfmiddlewaretoken: "{{ csrf_token }}" }
                    })
                });
            });
        </script>
{% endblock %}

games/word2def/templates/word2def/savedword_list.html
{% extends 'word2def/game_detail.html' %}

{% load i18n %}

{% block content_game %}
        <h2>{% trans "Saved words" %}</h2>
{% endblock %}